### ISSUE TITLE
Strings returned from Gosu should be frozen

### ISSUE THREAD

**Issue by jlnr** [jlnr/gosu#271]
Not sure who has posted this gist, but the character assignment shouldn't be possible:

https://gist.github.com/anonymous/9444709

Probably a SWIG bug?

**Comment by RavensKrag** [comment]
I don't understand why this is a problem. If this is not how things are supposed to go, what is the intended method of pasting text in?

If the String is frozen, doesn't that just freeze the buffer? You can't currently make a selection and then clear it from code. You would have to wait for the user to type something before that selection cleared.

**Comment by jlnr** [comment]
Even if the string returned by `#text` (or `#caption`, for example) is frozen, there is still the `#text=` setter to assign a new string. The gist "works" when you append a character using `+ "a"` instead of directly modifying the returned string.

What you describe sounds like a bug too, though! Or at least an unintended limitation.

**Comment by RavensKrag** [comment]
Wouldn't that be worse for performance? Assigning a new String would be more resource allocation and deallocation, constantly having to make new Strings instead of editing existing ones. I've heard this sort of thing with Strings is a severe performance hit in some applications (At least one web browser has this issue. I forget which one.)

Then there's the interface issue of having something that's a String, but can't be edited in the same way Strings are normally edited in Ruby. It sounds like your proposed interface would make these Strings immutable, which is not how they normally are in Ruby. I don't think C++ is normally like that either, so I'm quite confused.

Like, Hash freezes String keys, but that's only because the alternative would be chaos. I don't see how freezing these Strings makes things faster, cleaner, or more predictable.

**Comment by jlnr** [comment]
`Gosu::TextInput#text` creates a new Ruby string from `Gosu::TextInput::text()` in the C++ world for each call anyway, so there is not much additional overhead in freezing them.

You are right that Ruby code usually does not freeze strings before returning them. I'm not sure if that is a good or bad thing :) I think I'll just close this issue as "won't fix". Do you want to create a new issue for the TextInput limitation you have described above?

**Comment by RavensKrag** [comment]
I'm not sure...

I don't understand the design of TextInput, in terms of how it deals with text selection, so I'm not sure I'm the best person to phrase that bug report.

I personally try to avoid using the selection facility completely, because I just don't understand how it works. I kinda just want a buffer with some characters in it.

**Comment by jlnr** [comment]
That's not a bad approach anyway, the selection facility is mostly in `TextInput` for the benefit of the user who can select and delete things :) But it's definitely an under-documented API.
